name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        ref: my-other-branch
      name: Checkout
    - uses: ./.github/actions/automatic-tests
      name: Test
